allow for use of loginStandard functionality with docker login
docker/login-action pull request #50
Opened 2020-12-30 19:18 UTC by dbeal-wiser

Our pipelines actually supply the exact username and password without AWS credentials. I recognize this is unusual, but it should be possible to override the automatic detection functionality. This PR adds an option, `isECR`, which allows for the `loginStandard` functionality to be used even if ECR is detected.

Original behavior should not be altered unless user specifies `isECR` option.

suggest `Squash and Merge` for this PR.

2020-12-30 19:20 UTC, dbeal-wiser commented
are the test failures because my PR is running from another repo?

2021-04-01 15:17 UTC, mahdiamer approved these changes

2021-04-01 15:18 UTC, mahdiamer approved these changes
~~~~

2021-04-06 02:58 UTC, l2ichshop2 approved these changes

2021-12-16 12:35 UTC, crazy-max requested changes
Logs for failing tests are not available anymore. Can you rebase to trigger the CI again? Thx.

2021-12-16 12:35 UTC, crazy-max commented on action.yml
> +  isECR:
I think naming it `ecr` is enough

2021-12-20 10:06 UTC, crazy-max commented
#123

2021-12-20 10:06 UTC, closed without merging