Introduce codeql.yml to enable SAST scanning
docker/login-action pull request #622
Opened 2023-10-23 21:24 UTC by temenuzhka-thede

2023-10-23 23:25 UTC, crazy-max requested changes

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +      - '**/*.test.ts'
Can be simplified to:

```suggestion
    paths:
      - 'dist/**'
      - 'src/**'
```

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +      - '**/*.test.ts'
Same here:

```suggestion
    paths:
      - 'dist/**'
      - 'src/**'
```

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +    branches: [ "master" ]
Not recommended to pin branch for pr event. Please remove this line so it scans against any branches.

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +    branches: [ "master" ]
Should also include release branches:

```suggestion
    branches:
      - 'master'
      - 'releases/v*'
```

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +name: "CodeQL"
Name should be the exact same as the filename. This is a pattern that we use across our GitHub Actions to name workflows if we can keep it that way, thanks:

```suggestion
name: codeql
```

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +        language: [ 'javascript-typescript']
Prefer to avoid square brackets syntax:

```suggestion
        language:
          - 'javascript-typescript'
```

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +
Remove extra new line

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +
Remove extra new line here as well

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +    name: Analyze
Like the workflow name we prefer to keep the id of the job and avoid setting a custom name. Please remove this line.

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +    timeout-minutes: 360
Is this needed?

2023-10-23 23:25 UTC, crazy-max commented on .github/workflows/codeql.yml
> +        category: "/language:${{matrix.language}}"
Missing new line ending

2023-10-24 09:28 UTC, crazy-max approved these changes
@temenuzhka-thede I have made some changes related to my comments and squashed commits. Let me know if you have question.

2023-10-24 13:13 UTC, twelsh-aw approved these changes

2023-10-24 14:25 UTC, merged