docker auth: improve missing user/pwd
docker/login-action pull request #706
Opened 2024-04-30 19:52 UTC by Frankkkkk

Specify the "missing username and password" error message. This makes debugging the action easier when for example mistyping the username or the password.

Thanks and cheers!

2024-05-07 08:31 UTC, crazy-max commented
Thanks for this PR but I think the error message to users should remain generic. You can still check what value is empty in the login step (expand `Run docker/login-action@v3`):

![image](https://github.com/docker/login-action/assets/1951866/f91b3395-2641-4daf-8f33-80e5a50cbc21)

2024-05-15 10:17 UTC, crazy-max requested changes
Ok this change sounds good considering how other providers currently consume GitHub Actions.

You forgot to run `docker buildx bake pre-checkin` to update generated content btw, see https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request

Don't forget to squash commits as well. Thanks.

2024-05-15 10:17 UTC, crazy-max commented on src/docker.ts
> +
remove this extra new line

2024-05-16 07:58 UTC, Frankkkkk commented
Done, thanks.
Curious question: the dist file are so large; how do you make sure that a malicious user didn't embed some nefarious content in it ?
Subsidiary one: how do you deal with conflicts on MRs ? Do all contributors always have to rebase on every change on main?
Thanks!

2024-05-27 11:15 UTC, crazy-max approved these changes
LGTM thanks!

2024-05-27 11:16 UTC, merged